service: alda-backend # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline
   
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  fbWebhook:
    handler: src/handler.fbWebhook
    events:
      - http:
          method: POST
          path: fbWebhook
      - http:
          method: GET
          path: fbWebhook
  dialogflow:
    handler: src/handler.dialogflow
    events:
      - http:
          method: POST
          path: dialogflow
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: './gcloud.json'

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alda-user
        AttributeDefinitions:
          - AttributeName: PSID
            AttributeType: S
        KeySchema:
          - AttributeName: PSID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1 
          WriteCapacityUnits: 1
